# Generated by Django 3.1.5 on 2021-01-09 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fridge_food_name', models.CharField(max_length=120)),
                ('fridge_food_bought_date', models.DateField(default=datetime.date.today)),
                ('fridge_food_expire_date', models.DateField(default=datetime.datetime(2022, 1, 8, 23, 41, 10, 452879))),
                ('days_to_expire', models.IntegerField()),
                ('removed_from_fridge', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnownFoodsWithExpiryDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_food_name', models.CharField(max_length=120)),
                ('expiration_days', models.IntegerField()),
            ],
        ),
    ]
