# Generated by Django 3.1.5 on 2021-01-09 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgefoods',
            name='fridge_food_expire_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 8, 23, 41, 31, 268861)),
        ),
    ]
