# Generated by Django 3.1.5 on 2021-01-09 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_recipe', '0002_auto_20210108_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fridge_food_name', models.CharField(max_length=120)),
                ('fridge_food_bought_date', models.DateField(default=datetime.date.today)),
                ('fridge_food_expire_date', models.DateField(default=datetime.datetime(2022, 1, 8, 23, 45, 48, 737550))),
                ('days_to_expire', models.IntegerField()),
                ('removed_from_fridge', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='KnownFoodsWithExpiryDates',
            new_name='KnownExpiryDateFood',
        ),
        migrations.DeleteModel(
            name='FridgeFoods',
        ),
    ]
