# Generated by Django 3.1.5 on 2021-01-09 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_recipe', '0004_auto_20210109_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgefood',
            name='fridge_food_expire_date',
            field=models.DateField(default=datetime.date(2022, 1, 9)),
        ),
    ]
