# Generated by Django 3.1.5 on 2021-01-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_recipe', '0005_auto_20210109_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts/')),
            ],
        ),
    ]
